In [1]:
import scipy.io as spio
import numpy as np
import tensorflow as tf
import keras
from keras.models import Sequential
from keras.layers import Dense,Dropout

Using TensorFlow backend.


In [2]:
mat1 = spio.loadmat(r'C:\Chanakya\Textbooks\Semester-III\Project Seminar\BCI_left_filter.m', squeeze_me=True)
mat2 = spio.loadmat(r'C:\Chanakya\Textbooks\Semester-III\Project Seminar\BCI_right_filter.m', squeeze_me=True)

In [3]:
left_filter=mat1['left_filter_comb']
right_filter=mat2['right_filter_comb']

In [4]:
left_filter.shape
right_filter.shape

(19, 12, 18)

In [5]:
left_filter[1,:,:].shape


(12, 18)

In [6]:
x1=np.transpose(left_filter[1,:,:])
print(x1.shape)
x2=np.transpose(right_filter[1,:,:])
print(x2.shape)

(18, 12)
(18, 12)


In [7]:
combined=np.concatenate((x1,x2))
print(combined.shape)
x_train=combined

(36, 12)


In [8]:
p1=np.ones((18,1))
print(p1.shape)
p2=np.zeros((18,1))
print(p2.shape)
combined_p=np.concatenate((p1,p2))
print(combined_p.shape)
y_train=combined_p
print(y_train)

(18, 1)
(18, 1)
(36, 1)
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [9]:
model=Sequential()

model.add(Dense(48, input_dim=12, activation='tanh'))
model.add(Dropout(0.4))
model.add(Dense(48, activation='tanh'))
model.add(Dropout(0.4))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['accuracy'])

model.fit(x_train, y_train, epochs=400, batch_size=36)


Epoch 1/400
36/36 [==============================] - 1s 30ms/step - loss: 1.0779 - acc: 0.4722
Epoch 2/400
36/36 [==============================] - 0s 134us/step - loss: 0.8713 - acc: 0.5278
Epoch 3/400
36/36 [==============================] - 0s 212us/step - loss: 0.6655 - acc: 0.6389
Epoch 4/400
36/36 [==============================] - 0s 127us/step - loss: 0.6789 - acc: 0.6111
Epoch 5/400
36/36 [==============================] - 0s 184us/step - loss: 0.5478 - acc: 0.6667
Epoch 6/400
36/36 [==============================] - 0s 133us/step - loss: 0.5483 - acc: 0.8056
Epoch 7/400
36/36 [==============================] - 0s 200us/step - loss: 0.5388 - acc: 0.7500
Epoch 8/400
36/36 [==============================] - 0s 175us/step - loss: 0.5204 - acc: 0.7778
Epoch 9/400
36/36 [==============================] - 0s 126us/step - loss: 0.5091 - acc: 0.7500
Epoch 10/400
36/36 [==============================] - 0s 200us/step - loss: 0.5356 - acc: 0.7500
Epoch 11/400
36/36 [====================

Epoch 86/400
36/36 [==============================] - 0s 83us/step - loss: 0.0154 - acc: 1.0000
Epoch 87/400
36/36 [==============================] - 0s 89us/step - loss: 0.0187 - acc: 1.0000
Epoch 88/400
36/36 [==============================] - 0s 57us/step - loss: 0.0112 - acc: 1.0000
Epoch 89/400
36/36 [==============================] - 0s 83us/step - loss: 0.0106 - acc: 1.0000
Epoch 90/400
36/36 [==============================] - 0s 78us/step - loss: 0.0092 - acc: 1.0000
Epoch 91/400
36/36 [==============================] - 0s 172us/step - loss: 0.0164 - acc: 1.0000
Epoch 92/400
36/36 [==============================] - 0s 96us/step - loss: 0.0074 - acc: 1.0000
Epoch 93/400
36/36 [==============================] - 0s 58us/step - loss: 0.0171 - acc: 1.0000
Epoch 94/400
36/36 [==============================] - 0s 55us/step - loss: 0.0139 - acc: 1.0000
Epoch 95/400
36/36 [==============================] - 0s 89us/step - loss: 0.0082 - acc: 1.0000
Epoch 96/400
36/36 [===================

Epoch 171/400
36/36 [==============================] - 0s 111us/step - loss: 0.0023 - acc: 1.0000
Epoch 172/400
36/36 [==============================] - 0s 90us/step - loss: 0.0010 - acc: 1.0000
Epoch 173/400
36/36 [==============================] - 0s 40us/step - loss: 0.0018 - acc: 1.0000
Epoch 174/400
36/36 [==============================] - 0s 55us/step - loss: 0.0011 - acc: 1.0000
Epoch 175/400
36/36 [==============================] - 0s 83us/step - loss: 5.5166e-04 - acc: 1.0000
Epoch 176/400
36/36 [==============================] - 0s 69us/step - loss: 0.0011 - acc: 1.0000
Epoch 177/400
36/36 [==============================] - 0s 91us/step - loss: 5.6030e-04 - acc: 1.0000
Epoch 178/400
36/36 [==============================] - 0s 83us/step - loss: 0.0625 - acc: 0.9722
Epoch 179/400
36/36 [==============================] - 0s 141us/step - loss: 0.0033 - acc: 1.0000
Epoch 180/400
36/36 [==============================] - 0s 67us/step - loss: 0.0014 - acc: 1.0000
Epoch 181/400
36/36 

Epoch 253/400
36/36 [==============================] - 0s 66us/step - loss: 7.1607e-04 - acc: 1.0000
Epoch 254/400
36/36 [==============================] - 0s 97us/step - loss: 7.5699e-05 - acc: 1.0000
Epoch 255/400
36/36 [==============================] - 0s 96us/step - loss: 1.2217e-04 - acc: 1.0000
Epoch 256/400
36/36 [==============================] - 0s 58us/step - loss: 2.6940e-04 - acc: 1.0000
Epoch 257/400
36/36 [==============================] - 0s 55us/step - loss: 0.0016 - acc: 1.0000
Epoch 258/400
36/36 [==============================] - 0s 127us/step - loss: 1.1353e-04 - acc: 1.0000
Epoch 259/400
36/36 [==============================] - 0s 70us/step - loss: 4.1121e-05 - acc: 1.0000
Epoch 260/400
36/36 [==============================] - 0s 88us/step - loss: 1.0574e-04 - acc: 1.0000
Epoch 261/400
36/36 [==============================] - 0s 28us/step - loss: 8.2629e-05 - acc: 1.0000
Epoch 262/400
36/36 [==============================] - 0s 55us/step - loss: 9.5562e-05 - acc: 

Epoch 335/400
36/36 [==============================] - 0s 55us/step - loss: 1.1864e-04 - acc: 1.0000
Epoch 336/400
36/36 [==============================] - 0s 111us/step - loss: 7.8400e-04 - acc: 1.0000
Epoch 337/400
36/36 [==============================] - 0s 96us/step - loss: 9.7485e-05 - acc: 1.0000
Epoch 338/400
36/36 [==============================] - 0s 83us/step - loss: 7.8739e-05 - acc: 1.0000
Epoch 339/400
36/36 [==============================] - 0s 83us/step - loss: 3.2963e-04 - acc: 1.0000
Epoch 340/400
36/36 [==============================] - 0s 83us/step - loss: 8.8682e-05 - acc: 1.0000
Epoch 341/400
36/36 [==============================] - 0s 71us/step - loss: 2.9818e-04 - acc: 1.0000
Epoch 342/400
36/36 [==============================] - 0s 82us/step - loss: 2.6011e-04 - acc: 1.0000
Epoch 343/400
36/36 [==============================] - 0s 84us/step - loss: 0.0345 - acc: 0.9722
Epoch 344/400
36/36 [==============================] - 0s 88us/step - loss: 1.7859e-04 - acc: 

In [10]:
print(x1[1,:])

[ 0.84593608  0.002       1.          0.02992548  0.202       0.79608052
  0.0042464   0.6        -0.85808483  0.0017084   1.          0.95566932]


In [11]:
model.predict(x1[2:4,:])

array([[0.9999976],
       [0.9999975]], dtype=float32)

In [12]:
model.predict(x2)

array([[3.40661359e-06],
       [3.00621537e-06],
       [3.00621537e-06],
       [1.06551124e-04],
       [3.00621537e-06],
       [3.00621537e-06],
       [3.00621537e-06],
       [3.00621537e-06],
       [3.00621537e-06],
       [4.67342143e-05],
       [3.00621537e-06],
       [3.00621537e-06],
       [3.00621537e-06],
       [3.00621537e-06],
       [3.00621537e-06],
       [1.47169721e-05],
       [3.00621537e-06],
       [3.00621537e-06]], dtype=float32)